version: 2.1

jobs:
  my-new-job:  # job name 
    docker:     # Base Image for deployment
      - image: cimg/node:14.13.0
    steps:   # step or commands that has to run in the Job
      - checkout
      - run:
          name: install dependencies
          command: "node --version  && npm install"
      - run:
          name: run test
          command: "npm run test" 
  my-next-job: 
    docker:    
      - image: cimg/node:14.13.0
    steps:   
      - checkout
      - run:
          name: let me know 
          command: "echo my-new-job is done"

workflows:
  my-workflow:
    jobs:
      - my-new-job
      - my-next-job:
          requires:
          - my-new-job