version: 2.1
orbs:
  heroku: circleci/heroku@1.2.5

jobs:
  my-new-job:  # job name 
    docker:     # Base Image for deployment
      - image: cimg/node:14.13.0
    steps:   # step or commands that has to run in the Job
      - checkout
      - run:
          name: install dependencies
          command: "node --version  && npm install"
      - run:
          name: run test
          command: "npm run test" 

workflows:
  my-workflow:
    jobs:
      - my-new-job
        filters:
          branches: 
            only: master